class Letters:
    def __init__(self):
        self.a = ''
        self.b = ''
        self.c = ''
        self.d = ''
        self.e = ''
        self.f = ''
        self.g = ''
        self.h = ''
        self.i = ''
        self.j = ''
        self.k = ''
        self.l = ''
        self.m = ''
        self.n = ''
        self.o = ''
        self.p = ''
        self.q = ''
        self.r = ''
        self.s = ''
        self.t = ''
        self.u = ''
        self.v = ''
        self.w = ''
        self.x = ''
        self.y = ''
        self.z = ''
